// Re-export all services for easy importing
export * from '@/features/auth/services/authService'
export * from '@/features/classes/services/classService'
export * from '@/features/assignments/services/assignmentService'
export * from '@/features/submissions/services/submissionService'
export * from '@/features/users/services/userService'
export * from '@/features/ai/services/aiService'
export * from '@/features/reports/services/reportService'
export * from '@/features/subjects/services/subjectService'
export * from '@/features/notifications/services/notificationService'
export * from '@/features/audit/services/auditService'
